templateVersion: 1.0.0
defaultVersion: latest
version: "3.9"
services:
  $$id:
    # This MUST be stable for our documentation and
    # other automations.
    image: ghcr.io/coder/coder:$$core_version
    ports:
      - "7080:7080"
    environment:
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-$$config_POSTGRES_USER}:${POSTGRES_PASSWORD:-$$config_POSTGRES_PASSWORD}@database/${POSTGRES_DB:-$$config_POSTGRES_DB}?sslmode=disable"
      # You'll need to set CODER_ACCESS_URL to an IP or domain
      # that workspaces can reach. This cannot be localhost
      # or 127.0.0.1 for non-Docker templates!
      - CODER_ACCESS_URL=$$config_CODER_ACCESS_URL
    # If the coder user does not have write permissions on
    # the docker socket, you can uncomment the following
    # lines and set the group ID to one that has write
    # permissions on the docker socket.
    #group_add:
    #  - "998" # docker group on host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      $$id-database:
        condition: service_healthy
  $$id-database:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$$config_POSTGRES_USER # The PostgreSQL user (useful to connect to the database)
      - POSTGRES_PASSWORD=$$config_POSTGRES_PASSWORD # The PostgreSQL password (useful to connect to the database)
      - POSTGRES_DB=$$config_POSTGRES_DB # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - coder_data:/var/lib/postgresql/data # Use "docker volume rm coder_coder_data" to reset Coder
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  coder_data:
variables:
  - id: $$config_POSTGRES_USERNAME
    name: POSTGRES_USER
    label: Postgres DB Username | POSTGRES_USER
    defaultValue: coderUserPg
    description: 'Username for the PostgreSQL DB for Coder'
  - id: $$config_POSTGRES_PASSWORD
    name: POSTGRES_PASSWORD
    label: Postgres DB Password | POSTGRES_PASSWORD
    defaultValue: coderPasswordPg
    description: 'Password for the PostgreSQL DB for Coder'
  - id: $$config_POSTGRES_DB
    name: POSTGRES_DB
    label: Postgres DB Name | POSTGRES_DB
    defaultValue: coderDbPg
    description: 'Name for the PostgreSQL DB for Coder'
  - id: $$config_CODER_ACCESS_URL
    name: CODER_ACCESS_URL
    label: Coder Access URL | CODER_ACCESS_URL
    defaultValue: localhost
    description: 'URL for the Coder instance'
  - id: $$config_CODER_PORT
    name: CODER_PORT
    label: Coder Port | CODER_PORT
    defaultValue: 7080
    description: 'Port for the Coder instance'